'use strict';

const IDENTITY_CLASSES = ['position'];

const TAILWIND_CLASSES = {
  display: {
    block: 'block',
    'inline-block': 'inline-block',
    inline: 'inline',
    flex: 'flex',
    'inline-flex': 'inline-flex',
    table: 'table',
    'inline-table': 'inline-table',
    'table-caption': 'table-caption',
    'table-cell': 'table-cell',
    'table-column': 'table-column',
    'table-column-group': 'table-column-group',
    'table-footer-group': 'table-footer-group',
    'table-header-group': 'table-header-group',
    'table-row-group': 'table-row-group',
    'table-row': 'table-row',
    'flow-root': 'flow-root',
    grid: 'grid',
    'inline-grid': 'inline-grid',
    contents: 'contents',
    'list-item': 'list-item',
    none: 'hidden',
  },
  padding: {
    0: 'p-0',
    '0px': 'p-0',
    '1px': 'p-px',
    '0.125rem': 'p-0.5',
  },
  overflow: {
    auto: 'overflow-auto',
    hidden: 'overflow-hidden',
    visible: 'overflow-visible',
    scroll: 'overflow-scroll',
  },
  'overflow-x': {
    auto: 'overflow-x-auto',
    hidden: 'overflow-x-hidden',
    visible: 'overflow-x-visible',
    scroll: 'overflow-x-scroll',
  },
  'overflow-y': {
    auto: 'overflow-y-auto',
    hidden: 'overflow-y-hidden',
    visible: 'overflow-y-visible',
    scroll: 'overflow-y-scroll',
  },
  'border-style': {
    solid: 'border-solid',
    dashed: 'border-dashed',
    dotted: 'border-dotted',
    double: 'border-double',
    none: 'border-none',
  },
  opacity: {
    0: 'opacity-0',
    0.05: 'opacity-5',
    0.1: 'opacity-10',
    0.2: 'opacity-20',
    0.25: 'opacity-25',
    0.3: 'opacity-30',
    0.4: 'opacity-40',
    0.5: 'opacity-50',
    0.6: 'opacity-60',
    0.7: 'opacity-70',
    0.75: 'opacity-75',
    0.8: 'opacity-80',
    0.9: 'opacity-90',
    0.95: 'opacity-95',
    1: 'opacity-100',
  },
  float: {
    right: 'float-right',
    left: 'float-left',
    none: 'float-none',
  },
  clear: {
    left: 'clear-left',
    right: 'clear-right',
    both: 'clear-both',
    none: 'clear-none',
  },
  'object-fit': {
    contain: 'object-contain',
    cover: 'object-cover',
    fill: 'object-fill',
    none: 'object-none',
    'scale-down': 'object-scale-down',
  },
  'text-decoration': {
    underline: 'underline',
    'line-through': 'line-through',
    none: 'no-underline',
  },
  'font-weight': {
    100: 'font-thin',
    200: 'font-extralight',
    300: 'font-light',
    400: 'font-normal',
    500: 'font-medium',
    600: 'font-semibold',
    700: 'font-bold',
    800: 'font-extrabold',
    900: 'font-black',
  },
  'line-height': {
    1: 'leading-none',
    1.25: 'leading-tight',
    1.375: 'leading-snug',
    1.5: 'leading-normal',
    1.625: 'leading-relaxed',
    2: 'leading-loose',
  },
  'flex-wrap': {
    wrap: 'flex-wrap',
    'wrap-reverse': 'flex-wrap-reverse',
    nowrap: 'flex-nowrap',
  },
  'flex-grow': {
    0: 'flex-grow-0',
    1: 'flex-grow',
  },
  'flex-shrink': {
    0: 'flex-shrink-0',
    1: 'flex-shrink',
  },
  'justify-content': {
    'flex-start': 'justify-start',
    'flex-end': 'justify-end',
    center: 'justify-center',
    'space-between': 'justify-between',
    'space-around': 'justify-around',
    'space-evenly': 'justify-evenly',
  },
  'align-items': {
    'flex-start': 'items-start',
    'flex-end': 'items-end',
    center: 'items-center',
    baseline: 'items-baseline',
    stretch: 'items-stretch',
  },
  'text-align': {
    left: 'text-left',
    right: 'text-right',
    center: 'text-center',
    justify: 'text-justify',
  },
  'align-content': {
    center: 'content-center',
    'flex-start': 'content-start',
    'flex-end': 'content-end',
    'space-between': 'content-between',
    'space-around': 'content-around',
    'space-evenly': 'content-evenly',
  },
  'white-space': {
    normal: 'whitespace-normal',
    nowrap: 'whitespace-nowrap',
    pre: 'whitespace-pre',
    'pre-line': 'whitespace-pre-line',
    'pre-wrap': 'whitespace-pre-wrap',
  },
  margin: {},
  'overscroll-behavior': {
    auto: 'overscroll-auto',
    contain: 'overscroll-contain',
    none: 'overscroll-none',
  },
  'overscroll-behavior-y': {
    auto: 'overscroll-y-auto',
    contain: 'overscroll-y-contain',
    none: 'overscroll-y-none',
  },
  'overscroll-behavior-x': {
    auto: 'overscroll-x-auto',
    contain: 'overscroll-x-contain',
    none: 'overscroll-x-none',
  },
  visibility: {
    visible: 'visible',
    hidden: 'invisible',
  },
  'z-index': {
    0: 'z-0',
    10: 'z-10',
    20: 'z-20',
    30: 'z-30',
    40: 'z-40',
    50: 'z-50',
    auto: 'z-auto',
  },
  'flex-direction': {
    row: 'flex-row',
    'row-reverse': 'flex-row-reverse',
    column: 'flex-col',
    'column-reverse': 'flex-col-reverse',
  },
  flex: {
    '1 1 0%': 'flex-1',
    '1 1 auto': 'flex-auto',
    '0 1 auto': 'flex-initial',
    none: 'flex-none',
  },
  order: {
    1: 'order-1',
    2: 'order-2',
    3: 'order-3',
    4: 'order-4',
    5: 'order-5',
    6: 'order-6',
    7: 'order-7',
    8: 'order-8',
    9: 'order-9',
    10: 'order-10',
    11: 'order-11',
    12: 'order-12',
    '-9999': 'order-first',
    9999: 'order-last',
    0: 'order-none',
  },
  'grid-template-columns': {
    'repeat(1, minmax(0, 1fr))': 'grid-cols-1',
    'repeat(2, minmax(0, 1fr))': 'grid-cols-2',
    'repeat(3, minmax(0, 1fr))': 'grid-cols-3',
    'repeat(4, minmax(0, 1fr))': 'grid-cols-4',
    'repeat(5, minmax(0, 1fr))': 'grid-cols-5',
    'repeat(6, minmax(0, 1fr))': 'grid-cols-6',
    'repeat(7, minmax(0, 1fr))': 'grid-cols-7',
    'repeat(8, minmax(0, 1fr))': 'grid-cols-8',
    'repeat(9, minmax(0, 1fr))': 'grid-cols-9',
    'repeat(10, minmax(0, 1fr))': 'grid-cols-10',
    'repeat(11, minmax(0, 1fr))': 'grid-cols-11',
    'repeat(12, minmax(0, 1fr))': 'grid-cols-12',
    none: 'grid-cols-none',
  },
  'grid-auto-flow': {
    row: 'grid-flow-row',
    column: 'grid-flow-col',
    'row dense': 'grid-flow-row-dense',
    'column dense': 'grid-flow-col-dense',
  },
  'grid-auto-columns': {
    auto: 'auto-cols-auto',
    'min-content': 'auto-cols-min',
    'max-content': 'auto-cols-max',
    'minmax(0, 1fr)': 'auto-cols-fr',
  },
  'grid-auto-rows': {
    auto: 'auto-rows-auto',
    'min-content': 'auto-rows-min',
    'max-content': 'auto-rows-max',
    'minmax(0, 1fr)': 'auto-rows-fr',
  },
};

module.exports = {
  IDENTITY_CLASSES,
  TAILWIND_CLASSES,
};
